server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  application:
    name: gateway-server
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/EL2/protocol/openid-connect/certs
          authorities-claim-names: resource_access.eflexs_client.roles,realm_access.roles
         
  main:
    allow-bean-definition-overriding: true  
    web-application-type: reactive      
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      
      - id: eflexs-auth
        uri: lb://EFLEXS-AUTH
        predicates:
        - Path=/api/authservice/**
        
      - id: product-service
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/api/product-service/**
        
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/api/order-service/**
        
      - id: activity-service
        uri: lb://ACTIVITY-SERVICE
        predicates:
        - Path=/api/activity-service/**